Repository bryanmontalvan/trainboard, pull requests merged in 2023-03, with the labels that each got.

#7 Initial commit for landing-page
  package-lock.json
  package.json
  src/App.js
  src/components/Features.js
  src/components/Footer.js
  src/components/Hero.js
  src/components/Navbar.js
  src/components/Testimonials.js
  src/pages/Explore.js
  src/pages/Home.js
Labels: Frontend

#8 Landing page revamp
  public/logo192.png
  public/logo512.png
  public/trainboard_full.png
  public/trainboard_icon.png
  src/components/Features.js
  src/components/Footer.js
  src/components/Hero.js
  src/components/Navbar.js
  src/components/OurStory.js
  src/components/Testimonials.js
Labels: Frontend

#11 Updated signup
  src/App.js
  src/components/Hero.js
  src/pages/SignIn.js
  src/pages/SignUp.js
Labels: Frontend

#12 Workout cards now dynamic
  src/components/WorkoutCards.js
Labels: Frontend

#19 [FE/BE] Firebase Auth Integration
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/ProtectedRoute.js
  src/components/Navbar.js
  src/context/AuthContext.js
  src/firebase.js
  src/pages/Dashboard.js
  src/pages/SignIn.js
  src/pages/SignUp.js
Labels: UI/UX, Frontend, Backend

#22 Dashboard UI changes
  src/App.js
  src/components/Background.js
  src/components/FavoritesDropdown.js
  src/components/MyWorkoutsDropdown.js
  src/components/Searchbar.js
  src/pages/Dashboard.js
  src/pages/Favoriteworkouts.js
  src/pages/Myworkouts.js
Labels: UI/UX, Frontend

#27 About Us Page
  src/App.js
  src/components/Navbar.js
  src/pages/AboutUs.js
Labels: UI/UX, Frontend

#30 Updated Checkbox label
  src/components/WorkoutPublicCheckbox.js
Labels: Frontend

#31 Change PW, Profile, Delete Acc
  src/App.js
  src/components/Navbar.js
  src/pages/ChangePassword.js
  src/pages/DeleteAccount.js
  src/pages/Profile.js
Labels: Frontend, Backend

#33 Display email on /profile
  src/pages/Profile.js
Labels: UI/UX, Frontend
